"""Helpers for using conversation history in agent nodes."""

from __future__ import annotations

from langchain_core.messages import AIMessage, BaseMessage, HumanMessage, ToolMessage

MAX_RECENT_MESSAGES = 6


def _is_react_internal(msg) -> bool:
    """Return True for messages generated by the ReAct tool-calling loop.

    These are AIMessages that requested tool calls (even if they also have
    text content) and ToolMessages that carry raw tool results.  Neither
    should be shown to the synthesis LLM or surfaced to the user.
    """
    if isinstance(msg, ToolMessage):
        return True
    if isinstance(msg, AIMessage):
        if getattr(msg, "tool_calls", None):
            return True
    return False


def filter_conversation_messages(messages: list) -> list:
    """Strip ReAct-internal messages, keeping only user and assistant turns."""
    return [m for m in messages if not _is_react_internal(m)]


def format_recent_conversation(messages: list) -> str:
    """Format the most recent conversation turns for context (excluding the latest message).

    Filters out ReAct-internal messages (tool calls / tool results) so the
    synthesis LLM only sees actual user↔assistant conversation history.
    """
    if not messages or len(messages) <= 1:
        return ""

    conversational = filter_conversation_messages(messages)
    if len(conversational) <= 1:
        return ""

    previous = conversational[:-1]
    to_show = previous[-MAX_RECENT_MESSAGES:]
    parts = []
    for msg in to_show:
        if isinstance(msg, HumanMessage):
            content = getattr(msg, "content", str(msg))
            parts.append(f"User: {content}")
        elif isinstance(msg, AIMessage):
            content = getattr(msg, "content", str(msg))
            if isinstance(content, str) and len(content) > 500:
                content = content[:500] + "..."
            parts.append(f"Assistant: {content}")
    return "\n".join(parts)
